#stage 1
FROM node:14-alpine as node
WORKDIR /app
COPY / ./
RUN npm install
#RUN npm run build --prod
EXPOSE 4200
#stage 2
FROM nginx:alpine as dist
COPY --from=node /app/dist/signart/browser /usr/share/nginx/html
COPY --from=node /app//nginx.conf /etc/nginx/conf.d/default.conf